import type { Metadata } from "next";
import "@/styles/globals.css";

import "@fontsource-variable/outfit";
import "@fontsource-variable/overpass";
import "@fontsource-variable/merienda";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
